# Generated by Django 4.2.2 on 2023-07-02 18:34

import Loan.myapp.models.customers
import Loan.myapp.models.loans
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('user_type', models.CharField(choices=[('Admin', 'admin'), ('Customer', 'customer'), ('Merchant', 'merchant')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('late_fee_interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lending_starting_range', models.IntegerField()),
                ('lending_end_range', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_front', models.ImageField(upload_to=Loan.myapp.models.customers.upload_to)),
                ('id_back', models.ImageField(upload_to=Loan.myapp.models.customers.upload_to)),
                ('date_of_birth', models.DateField()),
                ('usercode', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('current_debt_outside', models.IntegerField()),
                ('credit_limit_outside', models.IntegerField()),
                ('credit_history_length', models.IntegerField()),
                ('pursuit_of_new_credit', models.IntegerField()),
                ('months_since_last_late_payment', models.IntegerField()),
                ('credit_mix', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.myuser',),
        ),
        migrations.CreateModel(
            name='MyLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.IntegerField()),
                ('accepted_amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.IntegerField()),
                ('no_of_months', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('offer_pdf', models.FileField(upload_to=Loan.myapp.models.loans.upload_to)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('due_date', models.DateField()),
                ('original_amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('Loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myloan')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.field'),
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.business')),
            ],
            options={
                'abstract': False,
            },
            bases=('myapp.myuser',),
        ),
    ]
