# Generated by Django 4.2.2 on 2023-07-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_loan_installments_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='amount_without_interest',
            field=models.DecimalField(decimal_places=2, default=60, max_digits=8),
            preserve_default=False,
        ),
    ]
