# Generated by Django 4.2.2 on 2023-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_installments_amount_without_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='installments',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
